---
language: android
jdk: oraclejdk7
android:
  components:
  - build-tools-21.1.1
  - android-21
env:
  global:
  - GRADLE_OPTS="-XX:MaxPermSize=4g -Xmx4g"
  - ANDROID_SDKS=android-14
  - ANDROID_TARGET=android-14
install:
- cp WordPress/gradle.properties-example WordPress/gradle.properties
script:
- "./gradlew -PdisablePreDex build"
